ezpublish:
    # Repositories configuration, setup default repository to support solr if enabled
    repositories:
        default:
            storage: ~
            search:
                engine: %search_engine%
                connection: default

    # Siteaccess configuration, with one siteaccess per default
    siteaccess:
        list: [site]
        groups:
            site_group: [site]
        default_siteaccess: site
        match:
            URIElement: 1

    # System settings, grouped by siteaccess and/or siteaccess group
    system:
        site_group:
            # These reflect the current installers, complete installation before you change them. For changing var_dir
            # it is recommended to install clean, then change setting before you start adding binary content, otherwise you'll
            # need to manually modify your database data to reflect this to avoid exceptions.
            var_dir: var/site
            # System languages. Note that by default, content, content types, and other data are in eng-GB locale,
            # so removing eng-GB from this ezlist may lead to errors or content not being shown, unless you change
            # all eng-GB data to other locales first.
            languages: [eng-GB]

        default:
            content_view:
                full:
                    full_ride:
                        template: "content/view/full/ride.html.twig"
                        match:
                            Identifier\ContentType: "ride"
                    inviqa_folder:
                        controller: AppBundle:Events:getAllEvents
                        template: "content/view/full/inviqa_events.html.twig"
                        match:
                            UrlAlias: "inviqa"
                            Identifier\ContentType: 'folder'
                    full_event:
                        template: "content/view/full/event.html.twig"
                        match:
                            Identifier\ContentType: "events"



                    root_folder:
                        template: "content/view/full/root_folder.html.twig"
                        match:
                            Identifier\ContentType: ['small_folder', 'folder']

                line:
                    line_point_of_interest:
                        template: 'content/view/line/point_of_interest.html.twig'
                        match:
                            Identifier\ContentType: ['point_of_interest']
                    line_ride:
                        template: "content/view/line/ride.html.twig"
                        match:
                            Identifier\ContentType: "ride"
                    inviqa_folder:
                        template: "content/view/line/events.html.twig"
                        match:
                            Identifier\ContentType: ["events"]

