<?php

/* eZPlatformUIBundle:Template:wraptemplate.js.twig */
class __TwigTemplate_06e7b3302535bacdac1c54cd8b74e2224c96a48e287984a61539dc90e399a0d7 extends eZ\Bundle\EzPublishDebugBundle\Twig\DebugTemplate
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        $__internal_ac58048ca7d7814e583035b7a7e8be461fdfdfacc4293af08f9a73b9ebfa0d06 = $this->env->getExtension("native_profiler");
        $__internal_ac58048ca7d7814e583035b7a7e8be461fdfdfacc4293af08f9a73b9ebfa0d06->enter($__internal_ac58048ca7d7814e583035b7a7e8be461fdfdfacc4293af08f9a73b9ebfa0d06_prof = new Twig_Profiler_Profile($this->getTemplateName(), "template", "eZPlatformUIBundle:Template:wraptemplate.js.twig"));

        // line 1
        echo "/**
 * This module has been dynamically generated by using the template
 * at \"";
        // line 3
        echo (isset($context["path"]) ? $context["path"] : $this->getContext($context, "path"));
        echo "\"
 */
YUI.add(\"";
        // line 5
        echo twig_escape_filter($this->env, (isset($context["module"]) ? $context["module"] : $this->getContext($context, "module")), "js", null, true);
        echo "\", function (Y) {
    var tpl = new Y.Template(Y.Handlebars);

    Y.Template.register(
        \"";
        // line 9
        echo twig_escape_filter($this->env, (isset($context["module"]) ? $context["module"] : $this->getContext($context, "module")), "js", null, true);
        echo "\",
        tpl.compile(\"";
        // line 10
        echo twig_escape_filter($this->env, (isset($context["templateCode"]) ? $context["templateCode"] : $this->getContext($context, "templateCode")), "js", null, true);
        echo "\")
    );
});
";
        
        $__internal_ac58048ca7d7814e583035b7a7e8be461fdfdfacc4293af08f9a73b9ebfa0d06->leave($__internal_ac58048ca7d7814e583035b7a7e8be461fdfdfacc4293af08f9a73b9ebfa0d06_prof);

    }

    public function getTemplateName()
    {
        return "eZPlatformUIBundle:Template:wraptemplate.js.twig";
    }

    public function isTraitable()
    {
        return false;
    }

    public function getDebugInfo()
    {
        return array (  42 => 10,  38 => 9,  31 => 5,  26 => 3,  22 => 1,);
    }
}
/* /***/
/*  * This module has been dynamically generated by using the template*/
/*  * at "{{ path|raw }}"*/
/*  *//* */
/* YUI.add("{{ module }}", function (Y) {*/
/*     var tpl = new Y.Template(Y.Handlebars);*/
/* */
/*     Y.Template.register(*/
/*         "{{ module }}",*/
/*         tpl.compile("{{ templateCode }}")*/
/*     );*/
/* });*/
/* */
